# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e28c4684a44240081bc6e8c9f6962757869885863030423dde6c1c4868a842dffa01fe1cca4522ed8c71a25408bdf6eb35ae3e13c97934c5c0f8516f7696dd

test:
  secret_key_base: 0610c48d34c4d8f643d7c7034944e083ffb767e84a6747f9ae514dc8b5b5a829aa3ce30cec253c7d638228ec979f0b28f9c24d5d41ae775e51f9ebebaeff705c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
